//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRepoBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen_Tag
    {
        public int id { get; set; }
        public int id_tag { get; set; }
        public int id_imagen { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
