//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRepoBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Imagen_Tag = new HashSet<Imagen_Tag>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Imagen_Tag> Imagen_Tag { get; set; }
    }
}
